name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      # We're not using `with: submodules` here because we can't do a
      # depth=1 clone. See below for more details.

    - name: Checkout flutter submodule
      # We can't do a depth-1 clone, because we need the most recent tag
      # so that Flutter knows its version and sees the constraint in our
      # pubspec is satisfied.  It's uncommon for flutter/flutter to go
      # more than 100 commits between tags. Fetch 1000 for good measure.
      run: |
        git submodule update --init --depth 1000

    - name: Add vendored flutter to PATH
      run: |
        echo vendor/flutter/bin >> "$GITHUB_PATH"

    - name: Run setup
      run: tools/setup-vendor-flutter

    - name: Download Flutter SDK artifacts (flutter precache)
      run: flutter precache --universal

    - name: Download our dependencies (flutter pub get)
      run: flutter pub get

    - name: Run tools/check
      run: TERM=dumb tools/check --all --verbose
