name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install FVM
      run: |
        brew tap leoafarias/fvm
        brew install fvm

    - name: Install Flutter SDK
      run: |
        fvm install
        fvm use

    - name: Load direnv (.envrc)
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Download Flutter SDK artifacts (flutter precache)
      run: flutter precache --universal

    - name: Download our dependencies (flutter pub get)
      run: flutter pub get

    - name: Run tools/check
      run: TERM=dumb tools/check --all --verbose
